services:
  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  compressor_worker:
    build: .
    container_name: celery_worker
    command: celery -A core.tasks worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - PYTHONPATH=/app

volumes:
  redis_data: